User_Prompt = "Start by creating a new coordinate system for the first part, setting the Euler angles to [0.0, 0.0, -90.0] and the translation vector to [0.0, 0.0, 0.0]. Next, draw a two-dimensional sketch on a new face, forming a loop with four lines: the first line starts at (0.0, 0.0) and ends at (0.375, 0.0); the second line starts at (0.375, 0.0) and ends at (0.375, 0.375); the third line starts at (0.375, 0.375) and ends at (0.0, 0.375); and the fourth line starts at (0.0, 0.375) and ends at (0.0, 0.0). Apply a sketch scale of 0.375 to this loop. Rotate the scaled sketch using the Euler angles [0.0, 0.0, -90.0] and translate it using the translation vector [0.0, 0.0, 0.0]. Finally, extrude the sketch 0.375 units in the direction opposite to the normal to create a solid body with final dimensions of 0.375 units in length, width, and height.For the second part, create another new coordinate system, setting the Euler angles to [-90.0, 0.0, -90.0] and the translation vector to [0.375, 0.125, 0.0]. Draw a new two-dimensional sketch on a new face, forming a loop with three lines: the first line starts at (0.0, 0.0) and ends at (0.25, 0.0); the second line starts at (0.25, 0.0) and ends at (0.25, 0.25); and the third line starts at (0.25, 0.25) and ends at (0.0, 0.0). Apply a sketch scale of 0.25 to this loop. Rotate the scaled sketch using the Euler angles [-90.0, 0.0, -90.0] and translate it using the translation vector [0.375, 0.125, 0.0]. Extrude the sketch 0.375 units in the direction of the normal and add this extruded shape to the existing cube. The final dimensions of this rectangular prism are 0.25 units in length, 0.25 units in width, and 0.375 units in height."

CoT_Prompt = """
Please create a CadQuery Python code to generate a model based on the following description. The reasoning process MUST BE enclosed within <think> </think> tags. The final CadQuery code MUST BE put in a python code block with ONLY the executable code inside the python box, nothing else.The final model is represented by r. In the <think> section, simulate the thought process of an engineer converting text descriptions into a CAD model. Follow these steps: 
    ➣ Stage 1: Description Analysis. Break down the description into different parts or components. Identify key parameters for each part (coordinate systems, Euler angles, translation vectors). Understand the spatial relationships and assembly sequence between parts. 
    ➣ Stage 2: Coordinate System Planning. Determine the coordinate systems used for each part. Parse how Euler angle rotations and translation vectors are applied. Ensure understanding of local-to-global coordinate system transformations. 
    ➣ Stage 3: Sketch Construction Strategy. Analyze how to create each 2D sketch (loops, lines, points). Determine scaling factors for each sketch. Plan how to transform sketches into 3D space. 
    ➣ Stage 4: Extrusion Operation Planning. Identify extrusion parameters for each part (direction, distance). Understand how to add extrusions to existing solids (new or merge). Verify dimensions after extrusion match the description. 
    ➣ Stage 5: Code Implementation Strategy. Plan the sequence of CadQuery operations. Determine necessary CadQuery functions and methods. Consider how to organize code for clarity and readability.
    ➣ Stage 6: When scaling in CadQuery. Directly scale the size, define a scaling factor variable, and apply the scaling factor directly to all coordinates and dimensions. Don’t try to use a non-existent ‘.scale()‘ method on Workplane objects. 

After your thinking process, provide clean, working CadQuery Python code to create the 3D model.Think step by step, but only keep a minimum draft for each thinking step, with 50 words at most. description:
"""
